#!/bin/bash

CHROOT_DIR=/tmp/chromiarchos_chroot

alreadythere() {
    echo "Error: The directory $CHROOT_DIR already exists" > /dev/tty3
    read
    exit 1
}

mustberoot() {
    echo "Error: You must be root to run this script" > /dev/tty3
    read
    exit 1
}

# Basic checks
[[ $UID = 0 ]] || mustberoot
[[ -e $CHROOT_DIR ]] && alreadythere

# OOM killer configuration
echo 0 > /proc/$$/oom_score_adj

# Mounts
mkdir $CHROOT_DIR
mount /dev/sda7 $CHROOT_DIR
mount -o bind /dev $CHROOT_DIR/dev  # TODO check that this is needed

# Internet
mount -o bind /etc/resolv.conf $CHROOT_DIR/etc/resolv.conf

# Chrome OS root
mount -o rbind / $CHROOT_DIR/media/chromeos


##########################################


# Main chroot
jchroot -n Arch $CHROOT_DIR /usr/local/bin/chromiarchos_sysinit


##########################################

cd /

. /sbin/killers

kill_with_open_files_on $CHROOT_DIR

cat /proc/mounts | awk '{print $2}' | grep "^$CHROOT_DIR" | sort -r | xargs umount

rmdir $CHROOT_DIR
