#!/bin/bash

mustberoot()
{
    echo "You must be root to run this script."
    exit 1
}

abort()
{
    echo $1
    exit 2
}

if [[ $# != 0 ]]
then
    echo "Usage: $0"
    echo
    echo "Restore an existing installation of Chromiarch OS after an automatic"
    echo "Chrome OS update."
    exit 3
fi

[[ $UID == 0 ]] || mustberoot


# Determine if / is read-only or already read-write
if [[ $(rootdev) != $(rootdev -s) ]]
then
    echo "Phase 1 of 2 : Disabling rootfs verification"
    ROOTDEV_PARTITION=$(rootdev -s | grep -o "[35]")
    KERNEL_PARTITION=$(( ROOTDEV_PARTITION - 1 ))
    case $KERNEL_PARTITION in
	2 | 4);;
	*) abort "Unable to determine current kernel partition (rootdev -s = $(rootdev -s))";;
    esac
    
    echo "Faking"
    echo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification --partitions $KERNEL_PARTITION

    echo "Phase 1 of 2 completed, please reboot and run $0 again to complete the restoring."
else
    if [[ ! -e /etc/init/tty3.conf ]]
    then
        echo "Phase 2 of 2 : Installing new upstart job for Arch and switching to synaptics"
        echo "Faking"
        echo cp /usr/local/share/tty3.conf /etc/init/
        echo mv /lib/udev/rules.d/75-synaptics.rules{,.bak}
        echo "Phase 2 of 2 completed, please reboot to start Chromiarch OS."
    else
        echo "Chromiarch OS should already be working on this Chromebook."
    fi
fi