#!/bin/bash
#
# License: MIT, see the LICENSE file
# Copyright © 2011, Guillaume Brunerie <guillaume.brunerie@[ens.fr|gmail.com]>

# Change the file descriptors to point to /dev/tty3
exec &>/dev/tty3

CHROOT_DIR=/tmp/chromiarchos_chroot

alreadythere() {
    echo "Error: The directory $CHROOT_DIR already exists, press Return to continue"
    read
    exit 1
}

mustberoot() {
    echo "Error: You must be root to run this script, press Return to continue"
    read
    exit 1
}

# Basic checks
[[ $UID = 0 ]] || mustberoot
[[ -e $CHROOT_DIR ]] && alreadythere

# OOM killer configuration
echo 0 > /proc/$$/oom_score_adj

# Mounts
mkdir $CHROOT_DIR
mount /dev/sda13 $CHROOT_DIR
mount -o bind /dev $CHROOT_DIR/dev  # TODO check that this is really needed

# Internet
rm $CHROOT_DIR/etc/resolv.conf
ln -s /media/chromeos/var/run/flimflam/resolv.conf $CHROOT_DIR/etc/resolv.conf

# Chrome OS root
mount -o rbind / $CHROOT_DIR/media/chromeos


##########################################


# Main chroot
chroot $CHROOT_DIR ${1:-/usr/local/bin/chromiarchos-init}


##########################################

cd /

. /sbin/killers

kill_with_open_files_on $CHROOT_DIR

cat /proc/mounts | awk '{print $2}' | grep "^$CHROOT_DIR" | tac | xargs umount

rmdir $CHROOT_DIR
